// file: upload.h
// contains the minimal html for uploading files

// minimized from setup.htm: configure the network
static const char setupContent[] PROGMEM =
R"==(<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport"content="width=device-width,initial-scale=1"><title>Setup WiFi</title></head><body style="width:300px"><h1>Setup WiFi</h1><div style="display:grid;grid-template-columns:10ch auto;grid-gap:1ch"><label>Devicename:</label><span id="d">xyz</span> <label>Network:</label><span><select id="n"style="width:12em"><option selected="selected"disabled="disabled">scanning...</option></select></span><label>Passphrase:</label><input id="pass"type="password"style="width:12em"></div><div style="text-align:right"><button id="b">Connect</button></div><hr><p style="text-align:right"><a id="nextLink"title="next step"href="/$update.htm"style="text-decoration:none">&gt;&gt;&gt;</a></p><script>var timer,d=document,state=0,oSel=d.getElementById("n");function check(){0==state?(state=1,fetch("/$sysinfo").then((function(e){return e.text()})).then((function(e){if(e.length>0){var t=JSON.parse(e).devicename;d.getElementById("d").textContent=t;var n=d.getElementById("nextLink");n.href=n.href.replace(/\/\/[^\/]+\//,"//"+t+"/"),state=2}}))):2==state?(state=3,fetch("/$scan").then((function(e){return e.text()})).then((function(e){0==e.length?state=2:(state=4,scanned(JSON.parse(e)))}))):4==state&&(window.clearInterval(timer),timer=0)}function scanned(e){oSel.innerHTML="";var t=d.createElement("option");t.value=0,t.text="select...",t.disabled=!0,oSel.options.add(t),e.forEach((function(e){var t=d.createElement("option");t.value=t.text=e.id,oSel.options.add(t)}))}d.getElementById("b").addEventListener("click",(function(){fetch("/$connect?n="+oSel.value+"&p="+d.getElementById("pass").value)})),timer=window.setInterval(check,800)</script></body></html>)==";

// minimized from upload.htm
static const char uploadContent[] PROGMEM =
R"==(<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport"content="width=device-width,initial-scale=1"><title>Upload</title></head><body style="width:300px"><h1>Upload</h1><div id="zone"style="width:260px;height:5em;padding:20px;background-color:#ddd">Drop here</div><a href="#i">I-Upload</a><hr><p style="text-align:right"><a href="/microide.htm">&gt;&gt;&gt;</a></p><script>function dragHelper(e){e.stopPropagation(),e.preventDefault()}function dropped(e){dragHelper(e);for(var n=e.dataTransfer.files,r=new FormData,t="/"+(location.hash?location.hash.substring(1)+"/":""),a=0;a<n.length;a++)r.append("file",n[a],t+n[a].name);fetch("/",{method:"POST",body:r}).then((function(){window.alert("done.")}))}var zoneObj=document.getElementById("zone");zoneObj.addEventListener("dragenter",dragHelper,!1),zoneObj.addEventListener("dragover",dragHelper,!1),zoneObj.addEventListener("drop",dropped,!1)</script></body></html>)==";

// minimized from boot.htm
static const char updateContent[] PROGMEM =
R"==(<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport"content="width=device-width,initial-scale=1"><title>Web Update</title></head><body style="width:300px"><h1>Web Update</h1><div style="display:grid"><progress value="0"max="1"></progress><span id="l"></span></div><div style="text-align:right"><button>Start</button></div><hr><p style="text-align:right"><a href="/updateicons.htm"title="next step"style="text-decoration:none">&gt;&gt;&gt;</a></p><script>var s=0,repo="https://homeding.github.io/",d=document,eBar=d.querySelector("progress"),done=0,work=null,timer=0,seed="?"+(new Date).valueOf();function log(e){d.querySelector("#l").innerText=e}function next(){s=3}function doS(){fetch(repo+"list.txt"+seed).then((function(e){return e.text()})).then((function(e){work=e.replace(/\r?\n/g,";").replace(/;$/,"").split(";"),eBar.max=work.length}))}function doF(){s=3;var e=work.shift();eBar.value=++done,log(e),"-"===e[0]?next():fetch(repo+e+seed).catch(next).then((function(e){return e.arrayBuffer()})).then((function(n){var t=new FormData;t.append("file",new Blob([n]),"/"+e),fetch("/",{method:"POST",body:t}).then(next)}))}location.hash?repo+=location.hash.substring(1)+"/":repo+="v09/",log("loading from:\n"+repo),d.querySelector("button").addEventListener("click",(function(){timer=window.setInterval((function(){0==s?(log("get..."),s++,doS()):1==s&&work?(log("clean..."),s++,fetch("/api/cleanweb").then((function(e){s++}))):3==s&&(work.length>0?doF():(window.clearInterval(timer),log("done")))}),100)}))</script></body></html>)==";
