# GitHub Action Workflow

name: Build Examples for ESP8266

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [develop]
  pull_request:
    branches: [master,develop]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Build Examples for ESP8266
  build-esp8266:
    name: build examples on ESP8266
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Run Arduino Compiler
      # see https://github.com/arduino/compile-sketches
      - name: Compile examples
        uses: arduino/compile-sketches@v1
        with:
          verbose: true
          platforms: |
            # Install ESP8266 platform via Boards Manager
            - name: "esp8266:esp8266"
              source-url: https://arduino.esp8266.com/stable/package_esp8266com_index.json
              version: 3.1.0
          fqbn: esp8266:esp8266:nodemcuv2
          libraries: |
            - source-path: ./
            - name: OneWire
            - name: DallasTemperature
            - name: RotaryEncoder
            - name: DHTNEW
            - name: my92xx
            - name: INA219_WE
            - name: Radio
            - name: RFCodes
            - name: LiquidCrystal_PCF8574
            - name: GFX Library for Arduino
            # - source-url: "https://github.com/moononournation/Arduino_GFX.git"
            - name: Adafruit GFX Library
            - name: Adafruit NeoPixel
            - name: PubSubClient
          sketch-paths: |
            - 'examples/standard'
            - 'examples/tutorial'
            - 'examples/plug'
            - 'examples/bulb'
            - 'examples/RFBridge'

          # size-report-sketch: 'ConnectionHandlerDemo'
          # enable-size-deltas-report: 'true'
          # sketches-report-path: ${{ env.SKETCHES_REPORTS_PATH }}
