# This is a basic workflow to help you get started with Actions

name: Checks

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "checks"
  checks:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: report environment
        run: export

        # Arduino - lint
      - name: Arduino-lint
        uses: arduino/arduino-lint-action@v1
        with:
          library-manager: update
          verbose: false

      # Run Arduino Compiler
      # see https://github.com/arduino/compile-sketches
      - name: Compile examples
        uses: arduino/compile-sketches@v1
        with:
          verbose: true
          platforms: |
            # Install ESP8266 platform via Boards Manager
            - name: esp8266:esp8266
              source-url: https://arduino.esp8266.com/stable/package_esp8266com_index.json
              version: 3.0.0
          fqbn: esp8266:esp8266:nodemcuv2
          libraries:
            - source-path: ./src
            - name: OneWire
            - name: LiquidCrystal_PCF8574
            - name: ESP8266 and ESP32 OLED driver for SSD1306 displays
            - name: Adafruit NeoPixel
            - name: RotaryEncoder
            - name: DHT sensor library for ESPx
            - name: my92xx

            #  ${{ env.LIBRARIES }}
          # size-report-sketch: 'ConnectionHandlerDemo'
          # enable-size-deltas-report: 'true'
          # sketches-report-path: ${{ env.SKETCHES_REPORTS_PATH }}
